<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Nylos.Helpdesk.Modules.Comments.Contracts\Nylos.Helpdesk.Modules.Comments.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\Nylos.Helpdesk.Shared.Abstractions\Nylos.Helpdesk.Shared.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Shared\Nylos.Helpdesk.Shared.Infrastructure\Nylos.Helpdesk.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
